spring:
  application:
    name: param-soft-discoveryserver
    
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
  instance:
    prefer-ip-address: true